version: '3.8'
services:
  mongo:
    image: mongo:jammy
    restart: always
    container_name: store-manager-api.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_cont:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    container_name: store-manager-api.mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017
    depends_on:
      - mongo

  store-manager:
    build: .
    container_name: store-manager-api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - mongo
